port: 9191

requests:
  - url: wss://beta-uat-ws.kidtopi.com/ws
    isStomp: false
  - url: wss://beta-qa-ws.kidtopi.com/ws
    headers:
      - key: room-id
        value: 6e13e241-06f3-453b-a076-5b68ea1b6d0a
      - key: authorization
        value: Bearer abc123
    isStomp: true
